### ISSUE TITLE
How to export to freeview?

### ISSUE THREAD

**Issue by polivaoren** [alexteghipco/brainSurfer-v2#2]
Thank you for the great program. How do I export it, so I can view it in Freeview? Whenever I try loading these files, freeview crashes.

**Comment by alexteghipco** [comment]
Of course, thanks! Do you mind sharing the file you're trying to export? I can't seem to replicate any issues on my end with the default files in ./brainMapsforTesting

**Comment by polivaoren** [comment]
The file is an atlas I'm working on, which is currently in MNI space (attached). It might be just me being novice to freesurfer. But any file that I export from BrainSurfer, creashes when I load it in freeview (either as surface or overlay).
[WholeBrain.nii.gz](https://github.com/alexteghipco/brainSurfer/files/13820572/WholeBrain.nii.gz)

Thank you so much for your help

**Comment by alexteghipco** [comment]
Hmm that's strange, when I export this file in brainSurfer (either using the automatically generated nifti when loading in or saving the overlay manually) it loads up successfully in Freeview. Just to check, does the [attached file](https://github.com/alexteghipco/brainSurfer/files/13821480/WholeBrain_CombinedClusters_FSSpace_LH.nii.gz) work for you? I can load this up on a lh.inflated fsaverage surface

<img width="1325" alt="Screenshot" src="https://github.com/alexteghipco/brainSurfer/assets/28403035/41ab3e6b-68ea-49c5-9263-ec427241367c">

**Comment by polivaoren** [comment]
Yes, I realized that myself. I should have just put the nifti file as the overlay (sometimes we have an idiot moment). So, thank you for the quick response, and your help, and for BrainSurfer (I found it really helpful in superimposing my atlas on the HCP-MMP1 atlas). On another note, I realized today that we are scientifically related. I'm the new post doc at both Jon Venezia lab, and Greg Hickok lab. I'm running the new dPCSA studies for Greg, that I'm assuming was once your baby. Small world :).

Bes of luck

Oren
________________________________

**Comment by polivaoren** [comment]
Hi. Second question. As I played with brainSurfer more, I ran into another issue. I want to convert the very nice annotation file that brainSurfer creates and upload it in freeview (I use the 'perceptually distinct' colormap). But (as you can see in the pics), when I load the annot file in freeview, some of the ROIs are missing (most notable V1). You have any ideas on how to solve this?

<img width="548" alt="Freeview2" src="https://github.com/alexteghipco/brainSurfer/assets/90558948/83d8cf8b-da19-46d4-adb5-4253fd21dbef">
<img width="525" alt="BrainSurfer1" src="https://github.com/alexteghipco/brainSurfer/assets/90558948/59248bbd-72e0-4277-bd09-336433c78656">
<img width="506" alt="BrainSurfer2" src="https://github.com/alexteghipco/brainSurfer/assets/90558948/933fdb6e-2fc9-42b4-b19a-eac02acc36c1">
<img width="579" alt="Freeview1" src="https://github.com/alexteghipco/brainSurfer/assets/90558948/6f43ef80-df68-4af6-9da2-7a54bfcef0a3">

**Comment by alexteghipco** [comment]
Looks like you caught a bug, thanks! Matlab normalizes rgb to be in the 256 range which is incompatible with other software. The values were being adjusted when exporting to .anot, but not fully. The below fix works on my end but do you mind testing it and letting me know if it also works for you? Then I'll push an update. 

To test you just need to download the below oSelect.mlapp, unzip it, and overwrite the existing one you have in ./brainSurfer-main/GUIs. Then just resave the file as an .annot in brainSurfer and load it up in freeview as you did before.

[oSelect.zip](https://github.com/alexteghipco/brainSurfer/files/13854320/oSelect.zip)

And what a small world indeed! Looking forward to seeing all the cool work you guys are up to.

**Comment by polivaoren** [comment]
First of all, thank you. The solution worked. However, I think I found two more bugs. When I load a nifti overlay on an fsaverage surface everything works smoothly. However, when I repeat the same process on an Fs_LR(s900,MSMAII) template it creates the overlay for the fsaverage instead. Also, I think the values of the voxels go out of whack if there is a missing number. for example, in the nifti atlas I gave you, the regions register well from region 1 (V1) all the way to 19. But because the value 20 is missing, there is incorrect registration for the same voxels between the volume and the surface (eg look how the voxels at the S1 region change value).

**Comment by alexteghipco** [comment]
Excellent, thanks for testing.

About the other two issues. The first I can't replicate on my end. 
![image](https://github.com/alexteghipco/brainSurfer/assets/28403035/e44644a6-bfef-4687-88aa-cbaee77b1ae6)
Perhaps you did not setup the path to the connectome workbench when you first started the GUI? If so you'll need to manually edit a text file in the main brainSurfer directory to update the path (see readme)

For the second issue, it would be helpful to have an image showing a demonstration as the atlas I'm looking at looks fine to me. A skipped value shouldn't matter. When projecting ROIs, the code looks for all unique values in the volume map, creates new maps for each one, projects each of them onto vertices, and then determines which ROI projection maps most strongly onto each vertex.

I'm going to go ahead and close this issue since we resolved what you initially opened but if you want to follow up on these other two just open another and we can troubleshoot what might be going wrong.
